import type { Item } from "./types";

export const ITEMS: Item[] = [
  // ---------- TRUTH GENERAL — LEVE ----------
  { id: "tg-l-1", category: "verdade_padrao", tier: "leve", text: "Qual foi a maior mentira que você já contou pros seus pais?" },
  { id: "tg-l-2", category: "verdade_padrao", tier: "leve", text: "Qual música embaraçosa você ouve escondido?" },
  { id: "tg-l-3", category: "verdade_padrao", tier: "leve", text: "Qual o vexame mais recente que você passou?" },
  { id: "tg-l-4", category: "verdade_padrao", tier: "leve", text: "Qual a coisa mais infantil que você ainda faz?" },
  { id: "tg-l-5", category: "verdade_padrao", tier: "leve", text: "Quem desse grupo você ligaria primeiro em uma emergência?" },
  { id: "tg-l-6", category: "verdade_padrao", tier: "leve", text: "Qual app você mais usa e tem vergonha de admitir?" },
  { id: "tg-l-7", category: "verdade_padrao", tier: "leve", text: "Já chorou vendo um filme infantil? Qual?" },
  { id: "tg-l-8", category: "verdade_padrao", tier: "leve", text: "Qual a comida estranha que você ama?" },
  { id: "tg-l-9", category: "verdade_padrao", tier: "leve", text: "Qual o último story que você tirou print escondido?" },
  { id: "tg-l-10", category: "verdade_padrao", tier: "leve", text: "Já fingiu estar doente pra escapar de algum compromisso? Conta." },
  { id: "tg-l-11", category: "verdade_padrao", tier: "leve", text: "Qual sua maior gafe em público?" },
  { id: "tg-l-12", category: "verdade_padrao", tier: "leve", text: "Qual famoso você acha que tem cara de ser chato pessoalmente?" },
  { id: "tg-l-13", category: "verdade_padrao", tier: "leve", text: "Qual é o apelido mais vergonhoso que você já teve?" },
  { id: "tg-l-14", category: "verdade_padrao", tier: "leve", text: "Qual a pior desculpa que você já inventou pra cancelar um plano?" },
  { id: "tg-l-15", category: "verdade_padrao", tier: "leve", text: "Já stalkeou alguém desse grupo? Até onde você foi?" },
  { id: "tg-l-16", category: "verdade_padrao", tier: "leve", text: "Qual a coisa mais idiota que você já fez pra impressionar alguém?" },
  { id: "tg-l-17", category: "verdade_padrao", tier: "leve", text: "Qual foi a última vez que você mentiu pra um amigo presente aqui?" },
  { id: "tg-l-18", category: "verdade_padrao", tier: "leve", text: "Você já roubou comida da geladeira de outra pessoa? Conta a situação." },
  { id: "tg-l-19", category: "verdade_padrao", tier: "leve", text: "Qual o hábito secreto que você tem quando está sozinho em casa?" },
  { id: "tg-l-20", category: "verdade_padrao", tier: "leve", text: "Qual foi a maior furada que você embarcou por causa de um amigo?" },
  { id: "tg-l-21", category: "verdade_padrao", tier: "leve", text: "O que você finge gostar só pra agradar alguém do grupo?" },
  { id: "tg-l-22", category: "verdade_padrao", tier: "leve", text: "Você já leu mensagem alheia sem permissão? De quem?" },
  { id: "tg-l-23", category: "verdade_padrao", tier: "leve", text: "Qual foi a última vez que você chorou de rir? Do quê?" },
  { id: "tg-l-24", category: "verdade_padrao", tier: "leve", text: "Qual a coisa mais estranha que você já pesquisou no Google?" },
  { id: "tg-l-25", category: "verdade_padrao", tier: "leve", text: "Você tem um alter ego com nome e personalidade? Descreve ele." },
  { id: "tg-l-26", category: "verdade_padrao", tier: "leve", text: "Qual foi o presente mais inútil que você já deu pra alguém?" },
  { id: "tg-l-27", category: "verdade_padrao", tier: "leve", text: "Qual a opinião impopular que você tem mas nunca fala por medo?" },
  { id: "tg-l-28", category: "verdade_padrao", tier: "leve", text: "Você já ficou com ciúmes de um amigo? Por quê?" },
  { id: "tg-l-29", category: "verdade_padrao", tier: "leve", text: "Qual a decisão mais impulsiva que você já tomou e se arrependeu?" },
  { id: "tg-l-30", category: "verdade_padrao", tier: "leve", text: "O que você faz quando está entediado que envergonharia seus amigos?" },
  { id: "tg-l-31", category: "verdade_padrao", tier: "leve", text: "Qual membro desse grupo te irritou recentemente mas você não falou nada?" },
  { id: "tg-l-32", category: "verdade_padrao", tier: "leve", text: "Qual é a sua maior insegurança física? Você pode ser honesto(a)." },
  { id: "tg-l-33", category: "verdade_padrao", tier: "leve", text: "Você já finco o pé numa briga e depois percebeu que estava errado? Conta." },
  { id: "tg-l-34", category: "verdade_padrao", tier: "leve", text: "Qual série ou filme você nunca terminou mas falou que assistiu?" },
  { id: "tg-l-35", category: "verdade_padrao", tier: "leve", text: "Você já mandou mensagem pra pessoa errada? O que disse?" },
  { id: "tg-l-36", category: "verdade_padrao", tier: "leve", text: "Qual a promessa que você fez pra si mesmo e nunca cumpriu?" },
  { id: "tg-l-37", category: "verdade_padrao", tier: "leve", text: "Você tem um ritual esquisito antes de dormir? Qual?" },
  { id: "tg-l-38", category: "verdade_padrao", tier: "leve", text: "Qual foi a última fofoca que você espalhou sem ter certeza se era verdade?" },
  { id: "tg-l-39", category: "verdade_padrao", tier: "leve", text: "Qual roupa você usa em casa que jamais usaria na rua?" },
  { id: "tg-l-40", category: "verdade_padrao", tier: "leve", text: "Você já se perdeu completamente tentando dar uma de corajoso(a)? Conta." },
  { id: "tg-l-42", category: "verdade_padrao", tier: "leve", text: "Qual é o talento inútil que você tem e secretamente se orgulha?" },

  // ---------- TRUTH GENERAL — +18 ----------
  { id: "tg-18-1", category: "verdade_padrao", tier: "+18", text: "Você já ficou com alguém presente nessa roda?" },
  { id: "tg-18-2", category: "verdade_padrao", tier: "+18", text: "Qual o lugar mais inusitado em que você já transou?" },
  { id: "tg-18-3", category: "verdade_padrao", tier: "+18", text: "Já mandou nudes? Pra quantas pessoas diferentes?" },
  { id: "tg-18-4", category: "verdade_padrao", tier: "+18", text: "Qual sua maior fantasia sexual?" },
  { id: "tg-18-5", category: "verdade_padrao", tier: "+18", text: "Já traiu alguém? E foi traído?" },
  { id: "tg-18-6", category: "verdade_padrao", tier: "+18", text: "Qual a história mais constrangedora que rolou na sua cama?" },
  { id: "tg-18-7", category: "verdade_padrao", tier: "+18", text: "Já pegou alguém muito mais velho ou mais novo? Quantos anos de diferença?" },
  { id: "tg-18-8", category: "verdade_padrao", tier: "+18", text: "Quando foi a última vez que você usou um aplicativo de relacionamento?" },
  { id: "tg-18-9", category: "verdade_padrao", tier: "+18", text: "Você ficaria com alguém nessa roda?" },
  { id: "tg-18-10", category: "verdade_padrao", tier: "+18", text: "Conta um 'ficante' secreto que ninguém aqui sabe." },
  { id: "tg-18-11", category: "verdade_padrao", tier: "+18", text: "Qual é o seu tipo físico que você nunca admitiria publicamente?" },
  { id: "tg-18-12", category: "verdade_padrao", tier: "+18", text: "Você já ficou com alguém comprometido(a)? Como foi?" },
  { id: "tg-18-13", category: "verdade_padrao", tier: "+18", text: "Qual a situação mais embaraçosa que você já passou na cama?" },
  { id: "tg-18-14", category: "verdade_padrao", tier: "+18", text: "Qual o kink que você nunca contou pra ninguém desse grupo?" },
  { id: "tg-18-15", category: "verdade_padrao", tier: "+18", text: "Você já teve atração por alguém do grupo aqui? Aponta ou confessa." },
  { id: "tg-18-16", category: "verdade_padrao", tier: "+18", text: "Qual foi a pior transa da sua vida e o que a fez tão ruim?" },
  { id: "tg-18-17", category: "verdade_padrao", tier: "+18", text: "Você já usou um álibi de amigo pra encobrir um encontro? Quem foi cúmplice?" },
  { id: "tg-18-18", category: "verdade_padrao", tier: "+18", text: "Qual a coisa mais ousada que você já propôs pra alguém e foi rejeitado(a)?" },
  { id: "tg-18-19", category: "verdade_padrao", tier: "+18", text: "Você já se apaixonou por alguém que não devia? O que aconteceu?" },
  { id: "tg-18-20", category: "verdade_padrao", tier: "+18", text: "Qual a mentira que você contou pra terminar um relacionamento?" },
  { id: "tg-18-21", category: "verdade_padrao", tier: "+18", text: "Você já fingiu durante o sexo? Conta como foi." },
  { id: "tg-18-22", category: "verdade_padrao", tier: "+18", text: "Qual app de relacionamento você já usou e deletou na vergonha?" },
  { id: "tg-18-23", category: "verdade_padrao", tier: "+18", text: "Você tem uma fantasia que acha que seu parceiro(a) jamais toparia?" },
  { id: "tg-18-24", category: "verdade_padrao", tier: "+18", text: "Qual foi o flerte mais ousado que alguém te fez? Você topou?" },
  { id: "tg-18-25", category: "verdade_padrao", tier: "+18", text: "Você já terminou com alguém por mensagem de texto? Como foi a resposta?" },
  { id: "tg-18-26", category: "verdade_padrao", tier: "+18", text: "Qual a coisa mais estranha que alguém já pediu na cama pra você?" },
  { id: "tg-18-27", category: "verdade_padrao", tier: "+18", text: "Você já ficou com dois(duas) da mesma roda de amigos? Como administrou?" },
  { id: "tg-18-28", category: "verdade_padrao", tier: "+18", text: "Qual relacionamento seu que esse grupo nunca aprovou e você sabe disso?" },
  { id: "tg-18-29", category: "verdade_padrao", tier: "+18", text: "Você já mandou nudes por engano pra pessoa errada? O que aconteceu?" },
  { id: "tg-18-30", category: "verdade_padrao", tier: "+18", text: "Qual foi a cantada mais criativa que você já deu? Funcionou?" },
  { id: "tg-18-31", category: "verdade_padrao", tier: "+18", text: "Você já terminou com alguém no aniversário ou data especial?" },
  { id: "tg-18-32", category: "verdade_padrao", tier: "+18", text: "Qual o seu record de tempo até transarem no primeiro encontro?" },
  { id: "tg-18-33", category: "verdade_padrao", tier: "+18", text: "Você já bloqueou alguém depois de ficar? Por quê?" },
  { id: "tg-18-34", category: "verdade_padrao", tier: "+18", text: "Qual foi o maior flagra que você já deu ou tomou?" },
  { id: "tg-18-35", category: "verdade_padrao", tier: "+18", text: "Você já ficou com alguém e fingiu que não tinha acontecido depois?" },
  { id: "tg-18-36", category: "verdade_padrao", tier: "+18", text: "Qual é o tipo de mensagem que você manda quando está bêbado(a) e se arrepende?" },
  { id: "tg-18-37", category: "verdade_padrao", tier: "+18", text: "Você já deu em cima de alguém enquanto estava em um relacionamento?" },
  { id: "tg-18-38", category: "verdade_padrao", tier: "+18", text: "Qual ex você ainda tem vontade de chamar às 2 da manhã?" },
  { id: "tg-18-39", category: "verdade_padrao", tier: "+18", text: "Você já usou alguém como plano B? E você já foi plano B de alguém?" },
  { id: "tg-18-40", category: "verdade_padrao", tier: "+18", text: "Qual foi a situação mais cinematográfica que já aconteceu na sua vida amorosa?" },

  // ---------- MOST LIKELY — LEVE ----------
  { id: "ml-l-1", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de abandonar os amigos por um amor?" },
  { id: "ml-l-2", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de virar milionário(a)?" },
  { id: "ml-l-3", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de cair em um golpe na internet?" },
  { id: "ml-l-4", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de chorar assistindo um filme?" },
  { id: "ml-l-5", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de perder o celular numa balada?" },
  { id: "ml-l-6", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de mudar de país sem avisar ninguém?" },
  { id: "ml-l-7", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de virar influencer?" },
  { id: "ml-l-8", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de esquecer um aniversário importante?" },
  { id: "ml-l-9",  category: "mais_provavel", tier: "leve", text: "Quem é mais provável de passar o réveillon sozinho(a) vendo série?" },
  { id: "ml-l-10", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de comprar uma coisa absurda no AliExpress às 3 da manhã?" },
  { id: "ml-l-11", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de virar professor(a) universitário(a)?" },
  { id: "ml-l-12", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de se perder num país estrangeiro sem bateria no celular?" },
  { id: "ml-l-13", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de criar um podcast e desistir no 3º episódio?" },
  { id: "ml-l-14", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de chorar de felicidade no casamento de outra pessoa?" },
  { id: "ml-l-15", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de aparecer no Domingão por algum talento bizarro?" },
  { id: "ml-l-16", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de adotar um animal de rua na mesma semana?" },
  { id: "ml-l-17", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de ser o primeiro do grupo a se casar?" },
  { id: "ml-l-18", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de esquecer onde estacionou o carro?" },
  { id: "ml-l-19", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de dar uma entrevista pra jornal reclamando do trânsito?" },
  { id: "ml-l-20", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de passar na Globo por acidente em alguma reportagem?" },
  { id: "ml-l-21", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de largar tudo e abrir um café no interior?" },
  { id: "ml-l-22", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de discutir com robô de atendimento e perder a paciência?" },
  { id: "ml-l-23", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de decorar todas as falas de um musical?" },
  { id: "ml-l-24", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de ser o(a) último(a) a saber de uma fofoca do grupo?" },
  { id: "ml-l-25", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de passar numa prova sem estudar nada?" },
  { id: "ml-l-26", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de aparecer no JN protestando por alguma causa?" },
  { id: "ml-l-27", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de comer a comida de todo mundo no almoço coletivo?" },
  { id: "ml-l-28", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de tatuar o nome de uma pessoa e se arrepender?" },
  { id: "ml-l-29", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de dar um piti num restaurante por causa do pedido errado?" },
  { id: "ml-l-30", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de comprar um cavalo por impulso?" },
  { id: "ml-l-31", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de ser expulso(a) de um voo?" },
  { id: "ml-l-32", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de ligar pra linha de atendimento ao cliente e agradecer no final?" },
  { id: "ml-l-33", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de dormir na mesa de trabalho sem perceber?" },
  { id: "ml-l-34", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de escrever um livro autobiográfico?" },
  { id: "ml-l-35", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de virar streamer de madrugada?" },
  { id: "ml-l-36", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de ir num show de um artista que odeia por amor a outra pessoa?" },
  { id: "ml-l-37", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de fazer uma dieta e abandonar no dia seguinte?" },
  { id: "ml-l-38", category: "mais_provavel", tier: "leve", text: "Quem é mais provável de criar uma religião nova acidentalmente?" },

  // ---------- MOST LIKELY — +18 ----------
  { id: "ml-18-1", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de abrir um OnlyFans?" },
  { id: "ml-18-2", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ficar com alguém no banheiro da balada?" },
  { id: "ml-18-3", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de mandar mensagem pro ex bêbado(a)?" },
  { id: "ml-18-4", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de topar um ménage?" },
  { id: "ml-18-5", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de já ter dormido com alguém no primeiro encontro?" },
  { id: "ml-18-6", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ter um crush secreto nessa roda?" },
  { id: "ml-18-7",  category: "mais_provavel", tier: "+18", text: "Quem é mais provável de transar numa praia pública?" },
  { id: "ml-18-8",  category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ter um relacionamento secreto por meses?" },
  { id: "ml-18-9",  category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ser ghostado(a) depois de uma noite incrível?" },
  { id: "ml-18-10", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ter mais de um interesse rolando ao mesmo tempo?" },
  { id: "ml-18-11", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de casar com alguém que conheceu há menos de 6 meses?" },
  { id: "ml-18-12", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de terminar um relacionamento via áudio no WhatsApp?" },
  { id: "ml-18-13", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ficar com o(a) ex do melhor amigo(a)?" },
  { id: "ml-18-14", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de já ter combinado um encontro mas nunca aparecer?" },
  { id: "ml-18-15", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de sair com alguém muito mais famoso(a) que ele(a)?" },
  { id: "ml-18-16", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de fazer uma tatuagem do(a) parceiro(a) e se separar em seguida?" },
  { id: "ml-18-17", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de provocar uma briga de casal por causa de like em foto?" },
  { id: "ml-18-18", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ter uma lista mental de exes rankeados por desempenho?" },
  { id: "ml-18-19", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ceder na primeira briga por medo de perder a pessoa?" },
  { id: "ml-18-20", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de se apaixonar por alguém completamente errado(a)?" },
  { id: "ml-18-21", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de pagar uma viagem inteira pra pessoa que está ficando?" },
  { id: "ml-18-22", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de já ter stalkeado um(a) ex às 3 da manhã?" },
  { id: "ml-18-23", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de se envolver com alguém do trabalho e complicar tudo?" },
  { id: "ml-18-24", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de fazer um escândalo numa festa de casamento alheio?" },
  { id: "ml-18-25", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de usar ciúmes como estratégia de sedução?" },
  { id: "ml-18-26", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de morar junto com alguém depois de 2 semanas de relacionamento?" },
  { id: "ml-18-27", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ter uma ex que ainda aparece do nada pedindo outra chance?" },
  { id: "ml-18-28", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de mandar um 'oi sumida(o)' totalmente sem contexto?" },
  { id: "ml-18-29", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de namorar alguém só pela aparência e depois se arrepender?" },
  { id: "ml-18-30", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de chorar de raiva depois de uma briga de relacionamento?" },
  { id: "ml-18-31", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de terminar com alguém no pior momento possível?" },
  { id: "ml-18-32", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ter um plano de sedução que nunca funciona?" },
  { id: "ml-18-33", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de dar em cima de alguém do grupo que nunca tocaria no assunto?" },
  { id: "ml-18-34", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de ter ficado com alguém dessa roda sem contar pra ninguém?" },
  { id: "ml-18-35", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de se envolver numa situação de triângulo amoroso sem querer?" },
  { id: "ml-18-36", category: "mais_provavel", tier: "+18", text: "Quem é mais provável de já ter mandado o screenshot errado pra pessoa errada?" },

  // ---------- MIMICA — LEVE ----------
  { id: "mi-l-1", category: "mimica", tier: "leve", text: "Mimica de um gato tentando derrubar algo da mesa." },
  { id: "mi-l-2", category: "mimica", tier: "leve", text: "Mimica de alguém pedindo uma marmita pelo iFood." },
  { id: "mi-l-3", category: "mimica", tier: "leve", text: "Mimica de uma cena de novela mexicana." },
  { id: "mi-l-4", category: "mimica", tier: "leve", text: "Mimica de um lutador de sumô tomando café da manhã." },
  { id: "mi-l-5", category: "mimica", tier: "leve", text: "Mimica de alguém tentando montar um móvel da IKEA." },
  { id: "mi-l-6", category: "mimica", tier: "leve", text: "Mimica do filme/série favorito do jogador à esquerda — sem falar." },
  { id: "mi-l-7", category: "mimica", tier: "leve", text: "Mimica de você acordando segunda de manhã." },
  { id: "mi-l-8", category: "mimica", tier: "leve", text: "Mimica de uma cena de horror em câmera lenta." },
  { id: "mi-l-9",  category: "mimica", tier: "leve", text: "Mímica de alguém tentando tirar selfie com a câmera frontal sem óculos." },
  { id: "mi-l-10", category: "mimica", tier: "leve", text: "Mímica de um personal trainer motivando um aluno que claramente quer desistir." },
  { id: "mi-l-11", category: "mimica", tier: "leve", text: "Mímica de alguém chegando atrasado numa reunião importante e tentando parecer que estava lá desde o começo." },
  { id: "mi-l-12", category: "mimica", tier: "leve", text: "Mímica de um cachorro encontrando seu dono depois de 8 horas." },
  { id: "mi-l-13", category: "mimica", tier: "leve", text: "Mímica de alguém abrindo um presente horrível e fingindo adorar." },
  { id: "mi-l-14", category: "mimica", tier: "leve", text: "Mímica de alguém tentando pagar a conta no Pix sem saber o valor exato." },
  { id: "mi-l-15", category: "mimica", tier: "leve", text: "Mímica de um influencer gravando conteúdo em público sem se envergonhar de nada." },
  { id: "mi-l-16", category: "mimica", tier: "leve", text: "Mímica de alguém que entrou no carro errado do Uber." },
  { id: "mi-l-17", category: "mimica", tier: "leve", text: "Mímica de um juiz de MasterChef provando algo e claramente odeia mas tenta ser educado." },
  { id: "mi-l-18", category: "mimica", tier: "leve", text: "Mímica de alguém recebendo uma notícia chocante pelo celular no meio de um velório." },
  { id: "mi-l-19", category: "mimica", tier: "leve", text: "Mímica de uma pessoa tentando dançar funk num casamento formal." },
  { id: "mi-l-20", category: "mimica", tier: "leve", text: "Mímica de alguém perdendo o WiFi no momento mais tenso de um jogo online." },
  { id: "mi-l-21", category: "mimica", tier: "leve", text: "Mímica de uma criança de 5 anos explicando o enredo de um filme de super-herói." },
  { id: "mi-l-22", category: "mimica", tier: "leve", text: "Mímica de alguém fingindo que entendeu uma piada que não entendeu." },
  { id: "mi-l-23", category: "mimica", tier: "leve", text: "Mímica de alguém fazendo pedido em drive-thru com o interfone quebrado." },
  { id: "mi-l-24", category: "mimica", tier: "leve", text: "Mímica de um pássaro aprendendo a voar pela primeira vez." },
  { id: "mi-l-25", category: "mimica", tier: "leve", text: "Mímica de alguém descobrindo que o restaurante não aceita cartão na hora de pagar." },
  { id: "mi-l-26", category: "mimica", tier: "leve", text: "Mímica de uma batalha épica entre duas galinhas num galinheiro." },
  { id: "mi-l-27", category: "mimica", tier: "leve", text: "Mímica de alguém tentando abrir uma embalagem lacrada sem tesoura." },
  { id: "mi-l-28", category: "mimica", tier: "leve", text: "Mímica de um político discursando sobre algo que claramente não entende nada." },
  { id: "mi-l-29", category: "mimica", tier: "leve", text: "Mímica de alguém que pisou em Lego descalço às 3 da manhã e não pode gritar." },
  { id: "mi-l-30", category: "mimica", tier: "leve", text: "Mímica de alguém tentando fazer yoga pela primeira vez assistindo tutorial no YouTube." },
  { id: "mi-l-31", category: "mimica", tier: "leve", text: "Mímica de um personagem da Disney fazendo compras no supermercado." },
  { id: "mi-l-32", category: "mimica", tier: "leve", text: "Mímica de alguém passando pela catraca do metrô e o cartão não passa." },
  { id: "mi-l-33", category: "mimica", tier: "leve", text: "Mímica de alguém que chegou antes do horário no encontro e não sabe o que fazer com as mãos." },
  { id: "mi-l-34", category: "mimica", tier: "leve", text: "Mímica de um pai tentando entender o TikTok do filho." },
  { id: "mi-l-35", category: "mimica", tier: "leve", text: "Mímica de alguém que tropeçou em público e tenta fingir que estava dançando." },
  { id: "mi-l-36", category: "mimica", tier: "leve", text: "Mímica de um chef francês que descobre que o prato dele foi comparado ao McDonald's." },
  { id: "mi-l-37", category: "mimica", tier: "leve", text: "Mímica de alguém tentando acordar alguém que dorme pesado antes do alarme." },
  { id: "mi-l-38", category: "mimica", tier: "leve", text: "Mímica do momento em que você percebe que saiu de casa sem o celular." },

  // ---------- MIMICA — +18 ----------
  { id: "mi-18-1", category: "mimica", tier: "+18", text: "Mimica do seu pior beijo (sem falar nada)." },
  { id: "mi-18-2", category: "mimica", tier: "+18", text: "Mimica de uma cantada péssima sendo dada pra você." },
  { id: "mi-18-3", category: "mimica", tier: "+18", text: "Mimica de um casal brigando em público depois da balada." },
  { id: "mi-18-4",  category: "mimica", tier: "+18", text: "Mímica de alguém tentando ser sexy dançando mas tropeça e tenta se recuperar." },
  { id: "mi-18-5",  category: "mimica", tier: "+18", text: "Mímica de alguém vendo a notificação de um ex às 2 da manhã e fingindo que não ligou." },
  { id: "mi-18-6",  category: "mimica", tier: "+18", text: "Mímica de alguém que acabou de receber uma cantada péssima e tenta ser gentil na recusa." },
  { id: "mi-18-7",  category: "mimica", tier: "+18", text: "Mímica de alguém enviando um áudio apaixonado e percebendo que mandou pro grupo errado." },
  { id: "mi-18-8",  category: "mimica", tier: "+18", text: "Mímica de alguém tentando ser discreto saindo cedo da casa de alguém na manhã seguinte." },
  { id: "mi-18-9",  category: "mimica", tier: "+18", text: "Mímica de uma briga de casal num restaurante chique onde nenhum dos dois levanta a voz mas os olhares dizem tudo." },
  { id: "mi-18-10", category: "mimica", tier: "+18", text: "Mímica de alguém que foi pego(a) lendo o celular do(a) parceiro(a) e tenta se explicar." },
  { id: "mi-18-11", category: "mimica", tier: "+18", text: "Mímica de alguém tentando dar uma de misterioso(a) no começo de um interesse e claramente falhando." },
  { id: "mi-18-12", category: "mimica", tier: "+18", text: "Mímica de dois exes se encontrando numa festa e fingindo que não se importam." },
  { id: "mi-18-13", category: "mimica", tier: "+18", text: "Mímica de alguém lendo uma mensagem apaixonada do(a) crush e tentando não sorrir na frente dos outros." },
  { id: "mi-18-14", category: "mimica", tier: "+18", text: "Mímica de alguém que acabou de descobrir que o(a) crush está namorando outra pessoa." },
  { id: "mi-18-15", category: "mimica", tier: "+18", text: "Mímica de alguém terminando um relacionamento por ligação e a ligação cai na metade." },
  { id: "mi-18-16", category: "mimica", tier: "+18", text: "Mímica de alguém que vai no primeiro encontro e o(a) parceiro(a) é completamente diferente das fotos." },
  { id: "mi-18-17", category: "mimica", tier: "+18", text: "Mímica de alguém que acabou de ser deixado no visto e decide enviar mais 3 mensagens." },
  { id: "mi-18-18", category: "mimica", tier: "+18", text: "Mímica de alguém flertando desajeitadamente num elevador que para em todos os andares." },
  { id: "mi-18-19", category: "mimica", tier: "+18", text: "Mímica de alguém acordando do lado de alguém que não reconhece e tentando lembrar o nome." },
  { id: "mi-18-20", category: "mimica", tier: "+18", text: "Mímica de alguém que descobre que o(a) ex casou enquanto scrollava o Instagram às 23h." },
  { id: "mi-18-21", category: "mimica", tier: "+18", text: "Mímica de alguém recebendo uma foto inesperada no Whatsapp e tendo que fechar rápido." },
  { id: "mi-18-22", category: "mimica", tier: "+18", text: "Mímica de alguém sendo apresentado(a) à família do(a) parceiro(a) pela primeira vez sem avisos." },
  { id: "mi-18-23", category: "mimica", tier: "+18", text: "Mímica de um casal fazendo as pazes depois de uma briga ridícula sem nenhum dos dois admitir que errou." },
  { id: "mi-18-24", category: "mimica", tier: "+18", text: "Mímica de alguém sendo ghostado(a) por alguém que está claramente online." },
  { id: "mi-18-25", category: "mimica", tier: "+18", text: "Mímica de alguém tentando dar uma de indiferente depois de mandar mensagem e esperar 4 horas por resposta." },
  { id: "mi-18-26", category: "mimica", tier: "+18", text: "Mímica de alguém que vai embora de uma festa e o(a) crush aparece 5 minutos depois." },
  { id: "mi-18-27", category: "mimica", tier: "+18", text: "Mímica de alguém sendo processado(a) num interrogatório policial sobre onde estava na noite anterior." },
  { id: "mi-18-28", category: "mimica", tier: "+18", text: "Mímica de alguém tentando ser romântico(a) e tudo dá errado ao mesmo tempo." },
  { id: "mi-18-29", category: "mimica", tier: "+18", text: "Mímica de alguém que deu match com o(a) chefe no Tinder e não sabe o que fazer." },
  { id: "mi-18-30", category: "mimica", tier: "+18", text: "Mímica de alguém tentando fazer uma surpresa romântica que vai completamente por água abaixo." },
  { id: "mi-18-31", category: "mimica", tier: "+18", text: "Mímica de um(a) ex aparecendo no local de trabalho sem avisar." },
  { id: "mi-18-32", category: "mimica", tier: "+18", text: "Mímica de alguém vendo o(a) ex com alguém novo(a) num bar e tentando fingir que está bem." },
  { id: "mi-18-33", category: "mimica", tier: "+18", text: "Mímica de alguém mandando um 'boa noite' cheio de intenção e recebendo um 'boa noite!' de volta com ponto de exclamação e nada mais." },

  // ---------- FOGO NO PARQUINHO — LEVE ----------
  {
    id: "fp-l-1",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Grave um story bem dramático",
    complementos: [
      "dizendo que sente saudade da sua infância",
      "dizendo que decidiu virar vegano amanhã",
      "anunciando que vai sair da cidade",
    ],
  },
  {
    id: "fp-l-2",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Mande um áudio agora pro contato escolhido pelo grupo",
    complementos: [
      "cantando o refrão da última música que você ouviu",
      "imitando um vendedor de mercado",
      "falando como se fosse um repórter esportivo",
    ],
  },
  {
    id: "fp-l-3",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Ligue pra um contato aleatório da sua agenda",
    complementos: [
      "perguntando se ele(a) já comeu",
      "fingindo que é uma pesquisa de satisfação",
      "pedindo conselho sobre uma planta murchando",
    ],
  },
  {
    id: "fp-l-4",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Faça uma selfie ridícula e poste no close friends",
    complementos: [
      "com a legenda 'novo eu, novo capítulo'",
      "marcando o jogador da sua direita",
      "com um filtro de animal",
    ],
  },
  {
    id: "fp-l-5",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Mande um elogio sincero por áudio",
    complementos: [
      "pra pessoa à sua esquerda agora",
      "pro contato que você menos fala no grupo",
      "pra alguém do grupo que você nunca elogiou antes",
    ],
  },
  {
    id: "fp-l-6",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Faça uma vaquinha relâmpago no grupo e pague um lanche pra pessoa que o grupo escolher",
    complementos: [
      "dentro de 10 minutos",
      "hoje à noite ainda",
      "até meia-noite",
    ],
  },
  {
    id: "fp-l-7",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Grave um vídeo de 15 segundos",
    complementos: [
      "imitando o bordão favorito de alguém do grupo",
      "fazendo a dancinha mais brega que você sabe",
      "anunciando uma 'notícia urgente' completamente inventada",
    ],
  },
  {
    id: "fp-l-8",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Poste nos stories um desafio",
    complementos: [
      "pedindo que seus seguidores adivinhem seu maior defeito",
      "onde você conta uma verdade constrangedora sem revelar quem estava envolvido",
      "dizendo que vai revelar um segredo amanhã — e não revelando",
    ],
  },
  {
    id: "fp-l-9",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Mande uma mensagem aleatória pra um familiar",
    complementos: [
      "dizendo que tem algo importante pra contar mas não conta",
      "perguntando qual foi o maior medo dele(a) na sua infância",
      "mandando um meme completamente fora de contexto",
    ],
  },
  {
    id: "fp-l-10",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Peça pra alguém do grupo escrever uma legenda",
    complementos: [
      "pra sua foto de perfil atual e você posta por 1 hora",
      "pra um story que você vai postar agora",
      "pra uma foto antiga da sua galeria escolhida pelo grupo",
    ],
  },
  {
    id: "fp-l-11",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Ligue em viva-voz pra alguém fora do grupo",
    complementos: [
      "e pergunte a opinião dele(a) sobre um dos jogadores",
      "e cante os parabéns sem contexto nenhum",
      "e convide pra aparecer agora mesmo",
    ],
  },
  {
    id: "fp-l-12",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Abra o Spotify e poste nos stories",
    complementos: [
      "a última música que você ouviu sem comentário nenhum",
      "sua playlist mais envergonhada com a legenda 'meu estado de espírito'",
      "a música que representa cada membro do grupo — em story único",
    ],
  },
  {
    id: "fp-l-13",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Mude seu status do WhatsApp agora pra",
    complementos: [
      "uma frase que o grupo vai escolher pra você",
      "'disponível pra casamento' e deixe por 30 minutos",
      "a última coisa que você pesquisou no Google",
    ],
  },
  {
    id: "fp-l-14",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Faça uma enquete nos stories",
    complementos: [
      "perguntando se você é chato(a) ou divertido(a) pra namorar",
      "com a pergunta 'devo mudar meu visual?' e mostre o resultado pro grupo",
      "perguntando qual é seu maior defeito segundo quem te conhece",
    ],
  },
  {
    id: "fp-l-15",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Deixe alguém do grupo escolher sua foto de perfil",
    complementos: [
      "da sua galeria — e troca por 1 hora",
      "de um app de redes sociais — e mantém até amanhã",
      "e posta com a legenda que eles escolherem",
    ],
  },
  {
    id: "fp-l-16",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Imite ao vivo por 1 minuto",
    complementos: [
      "o jeito de falar de alguém do grupo e o grupo tenta adivinhar quem",
      "um personagem famoso até alguém acertar",
      "um youtuber ou influencer escolhido pelo grupo",
    ],
  },
  {
    id: "fp-l-17",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Mostre sua galeria de fotos pro grupo",
    complementos: [
      "e deixe eles escolherem um photo dump pra você postar",
      "e eles escolhem a mais constrangedora — você precisa explicar o contexto",
      "e role até o ano passado — o grupo escolhe uma foto pra comentar",
    ],
  },
  {
    id: "fp-l-18",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Escreva uma resenha de 3 estrelas do Google",
    complementos: [
      "de um lugar que você amou mas com críticas completamente inventadas",
      "de um restaurante que você nunca foi mas fingindo que sim",
      "da casa de alguém do grupo como se fosse um hotel",
    ],
  },
  {
    id: "fp-l-19",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Grave um áudio caprichado",
    complementos: [
      "narrando a noite de hoje como se fosse um documentário da BBC",
      "fazendo a locução de um trailer de filme sobre sua vida",
      "descrevendo alguém do grupo como se fosse uma peça de museu",
    ],
  },
  {
    id: "fp-l-20",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Mande uma mensagem pra um contato do grupo de WhatsApp que você menos fala",
    complementos: [
      "perguntando como ele(a) está de verdade",
      "mandando um meme clássico como se fosse novidade",
      "convidando pra aparecer aqui agora",
    ],
  },
  {
    id: "fp-l-21",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Faça uma lista ao vivo",
    complementos: [
      "com os 3 melhores e 3 piores momentos do grupo esse ano",
      "do ranking de quem mais aparece nos seus planos e quem some",
      "das músicas que definem cada pessoa presente",
    ],
  },
  {
    id: "fp-l-22",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Deixe o grupo digitar uma mensagem no seu celular",
    complementos: [
      "e mande pro seu grupo familiar",
      "e poste como status",
      "e mande pra um colega de trabalho",
    ],
  },
  {
    id: "fp-l-23",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Faça um unboxing dramático",
    complementos: [
      "de qualquer objeto aleatório que tiver na bolsa ou mochila",
      "do seu porta-treco favorito fingindo que é produto de luxo",
      "da sua carteira como se fosse review de produto",
    ],
  },
  {
    id: "fp-l-24",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Monte uma playlist ao vivo pro grupo",
    complementos: [
      "com 5 músicas que definem sua semana",
      "com músicas tema de cada pessoa presente",
      "com as músicas mais vergonhosas que você tem salvas",
    ],
  },
  {
    id: "fp-l-25",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Grave um vídeo tutorial falso",
    complementos: [
      "de como sobreviver a uma reunião chata",
      "de como fazer amigos em 30 segundos",
      "de como parecer que está trabalhando sem fazer nada",
    ],
  },
  {
    id: "fp-l-26",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Poste nos stories uma foto sua",
    complementos: [
      "com o filtro mais feio que você achar e a legenda 'pronto pro verão'",
      "de quando você era criança com a legenda 'throwback icônico'",
      "completamente séria(o) com a legenda 'modo empresária(o) ativado'",
    ],
  },
  {
    id: "fp-l-27",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Mande um áudio de agradecimento",
    complementos: [
      "pra alguém que você nunca agradeceu de verdade",
      "pra quem te ajudou numa situação difícil recentemente",
      "pra um amigo do grupo dizendo por que ele(ela) é importante pra você",
    ],
  },
  {
    id: "fp-l-28",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Abra o iFood e monte um pedido imaginário",
    complementos: [
      "pro jantar perfeito da sua alma gêmea que você ainda não conheceu",
      "de tudo que você comeria se não tivesse nenhuma consequência",
      "e mostre pro grupo — eles decidem se você pede ou não",
    ],
  },
  {
    id: "fp-l-29",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Escreva uma autobiografia em 3 frases",
    complementos: [
      "e leia em voz alta com entonação de documentário",
      "e mande pra um familiar com a mensagem 'precisa saber disso'",
      "e poste como legenda de story sem contexto",
    ],
  },
  {
    id: "fp-l-30",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Invente uma notícia sobre alguém do grupo",
    complementos: [
      "e leia como se fosse manchete de jornal",
      "e mande pra ele(a) como se fosse verdade",
      "e faça o grupo votar se é crível ou não",
    ],
  },
  {
    id: "fp-l-31",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Faça uma estreia ao vivo",
    complementos: [
      "de uma dança que você inventou agora e dê um nome",
      "de uma expressão nova que você acabou de criar",
      "de um cumprimento exclusivo do grupo a partir de hoje",
    ],
  },
  {
    id: "fp-l-32",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Escreva um contrato de amizade ao vivo",
    complementos: [
      "com cláusulas ridículas que todos devem assinar no celular",
      "com multas para quem cancelar planos em cima da hora",
      "estabelecendo obrigações semanais entre o grupo",
    ],
  },
  {
    id: "fp-l-33",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Encontre agora na sua galeria",
    complementos: [
      "a foto mais aleatória que você tem e explique o contexto",
      "um screenshot antigo e leia o que está escrito pra todo mundo",
      "a selfie mais feia que você tem e poste nos stories",
    ],
  },
  {
    id: "fp-l-34",
    category: "fogo_no_parquinho",
    tier: "leve",
    base: "Ligue pro atendimento de alguma empresa",
    complementos: [
      "e faça uma reclamação totalmente inventada com a maior calma do mundo",
      "fingindo que é pesquisa de satisfação mas fazendo perguntas pessoais",
      "e diga que quer cancelar só pra ver o que oferecem",
    ],
  },

  // ---------- FOGO NO PARQUINHO — +18 ----------
  {
    id: "fp-18-1",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Mande mensagem pra última pessoa que você ficou",
    complementos: [
      "dizendo que tá com saudade",
      "perguntando o que ela está fazendo agora",
      "mandando uma foto sua tomando algo",
    ],
  },
  {
    id: "fp-18-2",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Mostre pro grupo a última conversa",
    complementos: [
      "com o seu ex",
      "com seu crush atual",
      "com a pessoa que você mais flertou no zap",
    ],
  },
  {
    id: "fp-18-3",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Poste um story...",
    complementos: [
      "com alguém do grupo e marque a pessoa dizendo 'parceiros no crime'",
      "com a legenda 'abrindo o OnlyFans em breve'",
      "com algum amigo ou amiga do grupo, e depois marcar um amigo ou amiga solteira dizendo que tá com uma versão gêmea dele(a) que precisa conhecer",
    ],
  },
  {
    id: "fp-18-4",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Curta as últimas 3 fotos no Instagram",
    complementos: [
      "do seu ex",
      "do crush da pessoa à sua direita",
      "de alguém que você nunca interagiu",
    ],
  },
  {
    id: "fp-18-5",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Mande uma mensagem misteriosa pro seu crush",
    complementos: [
      "dizendo 'tava pensando em você' e não responde mais nada",
      "perguntando 'ainda rola aquela vontade?' sem contexto",
      "mandando apenas um emoji sugestivo e esperando a resposta",
    ],
  },
  {
    id: "fp-18-6",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Abra o histórico de conversas com seu ex",
    complementos: [
      "e leia a última mensagem em voz alta pro grupo",
      "e mostre o emoji que ele(a) mais usava com você",
      "e conte o que estava sentindo na última vez que conversaram",
    ],
  },
  {
    id: "fp-18-7",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Poste um story enigmático direcionado",
    complementos: [
      "pro crush que o grupo vai escolher pra você",
      "que só faz sentido pra quem esteve com você mês passado",
      "que parece inocente mas é completamente sugestivo",
    ],
  },
  {
    id: "fp-18-9",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Mande um áudio pra alguém que o grupo vai escolher",
    complementos: [
      "dizendo que precisa falar com essa pessoa pessoalmente",
      "confessando algo que você nunca disse a ela",
      "fingindo que discou errado e veja a reação",
    ],
  },
  {
    id: "fp-18-10",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Curta agora uma foto antiga",
    complementos: [
      "de alguém com quem você teve um interesse mas nunca rolou",
      "do(a) crush secreto de alguém do grupo escolhido pelo grupo",
      "de alguém que te deixou no visto mais de uma vez",
    ],
  },
  {
    id: "fp-18-11",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Escreva e leia em voz alta",
    complementos: [
      "a cantada mais ousada que você toparia receber",
      "uma mensagem que você nunca teve coragem de mandar",
      "a descrição do seu tipo ideal sem filtro nenhum",
    ],
  },
  {
    id: "fp-18-12",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Faça uma ligação de voz agora",
    complementos: [
      "pra alguém que você ficou nos últimos 3 meses",
      "pra aquela pessoa que 'podia ter sido mas não foi'",
      "pra alguém que você sabe que está esperando seu contato",
    ],
  },
  {
    id: "fp-18-13",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Crie um perfil fake agora num app de relacionamento",
    complementos: [
      "com a bio mais honesta sobre você que já escreveu",
      "e mostre pro grupo quem você daria match",
      "e escolha as fotos que o grupo vai selecionar pra você",
    ],
  },
  {
    id: "fp-18-14",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Mostre pro grupo a seção 'recentes' do seu Instagram",
    complementos: [
      "e explique o contexto de cada perfil que você visitou",
      "e confesse qual desses é o crush atual",
      "e conte quantas vezes foi no mesmo perfil essa semana",
    ],
  },
  {
    id: "fp-18-15",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Mande uma mensagem de voz sensual",
    complementos: [
      "lendo qualquer frase banal como se fosse sedução total",
      "falando sobre o cardápio do restaurante mais próximo",
      "descrevendo o clima lá fora agora com entonação de cinema",
    ],
  },
  {
    id: "fp-18-16",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Desafie alguém fora do grupo agora",
    complementos: [
      "pra aparecer aqui em 20 minutos sem dar explicação",
      "pra adivinhar onde você está só com emojis de dica",
      "pra contar a última vez que pensou em você",
    ],
  },
  {
    id: "fp-18-17",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Revele pro grupo sem mostrar o celular",
    complementos: [
      "o que a última notificação de app de paquera dizia",
      "qual foi a última mensagem que você mandou e não teve resposta",
      "o nome do contato que você salvou com apelido no celular",
    ],
  },
  {
    id: "fp-18-18",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Grave um áudio de desculpas",
    complementos: [
      "pra alguém que você tratou mal num relacionamento passado",
      "pra alguém que você ficou e sumiu depois",
      "pra alguém que deixou você no visto e você ainda não processou",
    ],
  },
  {
    id: "fp-18-19",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Abra o Tinder ou app similar agora",
    complementos: [
      "e dê like em alguém que o grupo escolher no seu feed",
      "e mostre o match mais antigo que você nunca conversou",
      "e leia a bio mais estranha que você encontrar em 2 minutos",
    ],
  },
  {
    id: "fp-18-20",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Poste nos close friends agora",
    complementos: [
      "uma confissão que você nunca postaria no feed",
      "um ranking dos relacionamentos mais marcantes da sua vida",
      "a verdade sobre o seu status atual sem eufemismos",
    ],
  },
  {
    id: "fp-18-21",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Escreva e leia pra alguém do grupo",
    complementos: [
      "algo que você nunca teve coragem de falar pra essa pessoa",
      "como você descreveria a vibe entre vocês dois pra um estranho",
      "o motivo pelo qual você acha que nunca rolou algo entre vocês",
    ],
  },
  {
    id: "fp-18-22",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Faça um ranking ao vivo",
    complementos: [
      "dos seus relacionamentos da vida do pior ao melhor",
      "de quem do grupo você acha mais atraente — e leia em voz alta",
      "das situações mais caóticas que você já viveu por causa de alguém",
    ],
  },
  {
    id: "fp-18-23",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Mande uma mensagem direta pro interesse atual",
    complementos: [
      "dizendo algo que está guardando há tempo",
      "perguntando se ele(a) está livre nesse fim de semana sem mais explicações",
      "mandando uma foto sua agora com a legenda que o grupo vai criar",
    ],
  },
  {
    id: "fp-18-24",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Mostre sua lista de contatos salvos com apelido",
    complementos: [
      "e explique a história por trás de cada um",
      "e o grupo escolhe um pra você mandar mensagem agora",
      "e confesse qual deles você ainda pensa eventualmente",
    ],
  },
  {
    id: "fp-18-25",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Crie agora um story de confissão",
    complementos: [
      "contando algo que rola na sua vida amorosa que ninguém sabe",
      "revelando em quantas frentes você está jogando atualmente",
      "descrevendo o tipo de pessoa que você atrai inevitavelmente e não deveria",
    ],
  },
  {
    id: "fp-18-26",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Chame alguém de fora pra entrar na call ou aparecer",
    complementos: [
      "alguém que o grupo nunca viu mas sempre ouviu falar",
      "o crush atual sem contar pro grupo primeiro",
      "aquela pessoa que o grupo sabe que você gosta mas nunca assumiu",
    ],
  },
  {
    id: "fp-18-27",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Peça pra alguém do grupo responder uma mensagem no seu lugar",
    complementos: [
      "pra seu crush atual e você não pode interferir",
      "pra seu ex se ele(a) tiver mandado algo recentemente",
      "pra alguém com quem você está em clima de tensão",
    ],
  },
  {
    id: "fp-18-28",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Revele o apelido que você tem no celular de alguém",
    complementos: [
      "pedindo pra essa pessoa mostrar como você está salvo(a)",
      "contando o que você acha que essa pessoa te salvou como",
      "e o grupo vota no apelido mais provável",
    ],
  },
  {
    id: "fp-18-29",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Mande uma foto sua agora",
    complementos: [
      "com a legenda mais ousada que o grupo criar",
      "pra alguém que você sabe que ficaria surpreso(a) em receber",
      "pro grupo do trabalho fingindo que foi engano",
    ],
  },
  {
    id: "fp-18-30",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Abra o Instagram e siga alguém agora",
    complementos: [
      "que você estava com medo de seguir por parecer muito óbvio(a)",
      "que o grupo vai escolher na sua lista de sugestões",
      "que você já seguiu, deixou de seguir e fica na dúvida",
    ],
  },
  {
    id: "fp-18-31",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Declare ao vivo pra alguém do grupo",
    complementos: [
      "o motivo pelo qual você nunca daria em cima dessa pessoa",
      "o motivo pelo qual você acha que podia ter rolado algo diferente",
      "uma qualidade que você admira nessa pessoa que nunca falou",
    ],
  },
  {
    id: "fp-18-32",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Releia em voz alta pra todo grupo",
    complementos: [
      "a última mensagem que você recebeu de alguém que estava interessado(a) em você",
      "o último elogio sincero que alguém te mandou",
      "a última vez que alguém te pediu um encontro e você negou",
    ],
  },
  {
    id: "fp-18-33",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Com o celular da pessoa à sua direita em mãos, abra a galeria de fotos. Você tem 1 min para...",
    complementos: [
      "encontrar a foto mais sensual que ela já tirou na frente do espelho (e mostrar rápido pro grupo)",
      "achar um print de conversa picante ou fofoca comprometedora e ler a primeira linha",
      "favoritar (coraçãozinho) a foto mais constrangedora que ela tem guardada e depois mostrar para o grupo",
    ],
  },
  {
    id: "fp-18-34",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Pegue o celular da pessoa à sua esquerda e vá direto para a lista de contatos bloqueados dela...",
    complementos: [
      "escolha um nome aleatório e exija que ela explique pro grupo por que está bloqueado",
      "desbloqueie temporariamente um ex, olhe a foto de perfil em silêncio e bloqueie de novo",
      "leia os três primeiros nomes da lista em voz alta pra ver se alguém do grupo conhece",
    ],
  },
  {
    id: "fp-18-42",
    category: "fogo_no_parquinho",
    tier: "+18",
    base: "Com o celular da pessoa à sua direita, abra a conversa do WhatsApp com o(a) melhor amigo(a) dela e...",
    complementos: [
      "mande um áudio falando: 'Acho que fiz uma besteira enorme ontem à noite, me liga urgente'",
      "digite: 'Você não vai acreditar com quem eu fiquei de novo?'",
      "mande um áudio gemendo bem baixo falando o nome de alguém que essa pessoa conhece e apague apenas quando a pessoa visualizar ou responder"    ],
  },
  {
  id: "fp-18-43",
  category: "fogo_no_parquinho",
  tier: "+18",
  base: "Dê 3 títulos de 'prêmio' para pessoas do grupo",
  complementos: [
    "'mais gostoso', 'mais gado', 'mais surtado'",
    "'que mais beija mal', 'que mais dá bandeira', 'mais fácil'",
    "'mais rico', 'mais pobre', 'mais piranha'",
  ],
}
];